name: ${project.name}
main: name.richardson.james.bukkit.starterkit.StarterKit
author: grandwazir
description: Give items to new players.
website: https://grandwazir.github.com/StarterKit
version: ${project.version}
commands:
  sk:
    description: 'StarterKit root command'
    alias: [starterkit]
    usage: '/sk'
